### ISSUE TITLE
Use Travis CI for automated testing

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [BerkhanBerkdemir/list-of-houses#2]
We need a CI system for `bundle exec rails test` and `bundle exec rubocop`. 

Example of `.travis.yml`

```yaml
language: ruby
sudo: false
rvm:
  - 2.3.4
  - 2.4.1

addons:
  postgresql: "9.6"

env:
  - RAILS_ENV=test

cache:
  directories:
    - vendor/bundle
    - node_modules

jobs:
  include:
  - stage: test
    script: bundle exec rails test
  -
    stage: bundle exec rubocop
```
